### ISSUE TITLE
Outdated schema

### ISSUE THREAD

**Issue by jncfa** [osrf/redf#18]
As the title indicates, the [schema](https://github.com/osrf/redf/blob/9c2e096ebb90fee3a2bad877aaf184f834c6e8c1/redf.schema.json) on master is outdated since this commit was introduced: https://github.com/osrf/redf/commit/80aaeb9d255e90ce7d1125e70fdedeea790e2127

I can make an MR to regenerate this and fix this file, but would it be possible to consider some solution that forces this file to always be up to date? Maybe a job on the pipeline that checks for it and maybe auto-generates it?

**Comment by koonpeng** [comment]
Thank you for reporting the issue, I agree that the CI is lacking, we should have a test to check if the schema is changed. I will see what I can do to improve it.

**Comment by koonpeng** [comment]
fixed by #19
